#pragma once
#include <string>
#include <vector>
#include <queue>
#include <memory>
#include <unordered_map>
#include <mutex>
#include <atomic>
#include <thread>
#include <functional>
#include <cstdint>
#include <climits>
#include <cmath>
#include <cstdlib>
#include <algorithm>
#include <nlohmann/json.hpp>

namespace archisys {

// ─────────────────────────────────────────────────────────────────────────────
// 1. Request Data Structures
// ─────────────────────────────────────────────────────────────────────────────

enum class RequestStatus {
    Created,     // Generated by client
    InQueue,     // Waiting in component FIFO queue
    Processing,  // Actively occupying a worker slot
    Completed,   // Successfully completed
    Dropped,     // Dropped on queue overflow
    Failed       // Error in routing or execution
};

struct RouteHop {
    int componentId = 0;
    std::string componentName = "";
    double queueWaitTimeMs = 0.0;
    double processingTimeMs = 0.0;
};

struct Request {
    uint64_t id = 0;
    int clientId = 0;
    RequestStatus status = RequestStatus::Created;
    int currentComponentId = -1;

    double createdAtSec = 0.0;
    double completedAtSec = 0.0;

    double totalQueueWaitMs = 0.0;
    double totalProcessingMs = 0.0;

    std::vector<RouteHop> route;

    bool isDone() const {
        return status == RequestStatus::Completed ||
               status == RequestStatus::Dropped ||
               status == RequestStatus::Failed;
    }

    bool isSuccess() const {
        return status == RequestStatus::Completed;
    }

    double totalRoundTripMs() const {
        return totalQueueWaitMs + totalProcessingMs;
    }
};

// ─────────────────────────────────────────────────────────────────────────────
// 2. Telemetry Metrics Structures
// ─────────────────────────────────────────────────────────────────────────────

struct ComponentMetrics {
    int id = 0;
    std::string name = "";
    std::string type = "";

    int queueDepth = 0;
    int maxQueue = 0;
    double cpuUsagePct = 0.0;

    uint64_t requestsReceived = 0;
    uint64_t requestsCompleted = 0;
    uint64_t requestsDropped = 0;

    double avgProcessingMs = 0.0;
    double avgQueueWaitMs = 0.0;
    double throughputPerSec = 0.0;
};

struct SystemMetrics {
    double simTimeSec = 0.0;

    uint64_t totalRequests = 0;
    uint64_t completed = 0;
    uint64_t failed = 0;
    uint64_t dropped = 0;
    uint64_t inFlight = 0;

    double avgLatencyMs = 0.0;
    double p99LatencyMs = 0.0;
    double throughputPerSec = 0.0;

    std::unordered_map<int, ComponentMetrics> perComponent;
};

// ─────────────────────────────────────────────────────────────────────────────
// 3. Component Base Class (OOP)
// ─────────────────────────────────────────────────────────────────────────────

struct Worker {
    std::shared_ptr<Request> activeRequest = nullptr;
    double remainingTimeMs = 0.0;
    double totalTimeMs = 0.0;
};

class Component {
public:
    Component(int id, std::string name, std::string type);
    virtual ~Component() = default;

    // Topology
    int getId() const { return id_; }
    const std::string& getName() const { return name_; }
    const std::string& getType() const { return type_; }

    void addOutgoing(Component* next);
    void addIncoming(Component* prev);
    const std::vector<Component*>& getOutgoing() const { return outgoing_; }
    const std::vector<Component*>& getIncoming() const { return incoming_; }

    // Configuration
    int maxQueue = 100;
    double procTimeMs = 20.0;
    int instances = 1;
    int cpuCores = 1;

    // Core Lifecycle (Polymorphic)
    virtual bool receiveRequest(std::shared_ptr<Request> req, double simNowSec);
    virtual std::vector<std::shared_ptr<Request>> update(double dtSec, double simNowSec);
    virtual double calculateProcessTime(const std::shared_ptr<Request>& req);
    virtual void forwardRequest(std::shared_ptr<Request> req, double simNowSec);

    // Metrics & State
    ComponentMetrics getMetrics() const;
    void reset();

    int getQueueDepth() const;
    int getBusyWorkers() const;
    double getCpuUsagePct() const;

protected:
    int id_;
    std::string name_;
    std::string type_;

    std::vector<Component*> outgoing_;
    std::vector<Component*> incoming_;

    std::queue<std::pair<std::shared_ptr<Request>, double>> waitQueue_;
    std::vector<Worker> workers_;

    uint64_t rxCount_ = 0;
    uint64_t txCount_ = 0;
    uint64_t droppedCount_ = 0;
    double sumProcessingMs_ = 0.0;
    double sumQueueWaitMs_ = 0.0;
    double cpuUsagePct_ = 0.0;
    double throughput_ = 0.0;

    uint64_t lastTxCount_ = 0;
    double lastMetricTimeSec_ = 0.0;

    mutable std::mutex compMutex_;
};

// ─────────────────────────────────────────────────────────────────────────────
// 4. Specialized Component Subclasses (Polymorphism & OOP)
// ─────────────────────────────────────────────────────────────────────────────

// Client — Traffic Entry Point
class Client : public Component {
public:
    Client(int id, std::string name);
};

// Server — Multi-Instance Compute Worker Pool
class Server : public Component {
public:
    Server(int id, std::string name);
};

// Database — Persistence tier with read/write query latency & locks
class Database : public Component {
public:
    double writeMultiplier = 2.0;

    Database(int id, std::string name);
    double calculateProcessTime(const std::shared_ptr<Request>& req) override;
};

// LoadBalancer — Distributes traffic via Least Connections or Round Robin
enum class LBAlgorithm { RoundRobin, LeastConnections, Random };

class LoadBalancer : public Component {
public:
    LBAlgorithm algorithm = LBAlgorithm::LeastConnections;

    LoadBalancer(int id, std::string name);
    void forwardRequest(std::shared_ptr<Request> req, double simNowSec) override;

private:
    size_t rrIndex_ = 0;
};

// RedisCache — In-memory caching tier (80% Hit -> 1ms, 20% Miss -> Database)
class RedisCache : public Component {
public:
    double hitRatio = 0.80;

    RedisCache(int id, std::string name);
    double calculateProcessTime(const std::shared_ptr<Request>& req) override;
    void forwardRequest(std::shared_ptr<Request> req, double simNowSec) override;

private:
    bool isCacheHit(const std::shared_ptr<Request>& req) const;
};

// MessageQueue — Asynchronous queue buffer
class MessageQueue : public Component {
public:
    MessageQueue(int id, std::string name);
};

// ─────────────────────────────────────────────────────────────────────────────
// 5. Simulation Engine Coordinator
// ─────────────────────────────────────────────────────────────────────────────

struct SimulationConfig {
    double durationSec = 60.0;
    double tickSec = 0.01;
    double requestRatePerSec = 100.0;
    uint64_t totalRequests = 0;
    int clientId = -1;
    uint64_t seed = 42;
};

class SimulationEngine {
public:
    SimulationEngine();
    ~SimulationEngine();

    SimulationEngine(const SimulationEngine&) = delete;
    SimulationEngine& operator=(const SimulationEngine&) = delete;

    void addComponent(std::shared_ptr<Component> comp);
    void addEdge(int fromId, int toId);
    void setEntryPoint(int componentId);

    SimulationConfig& config() { return config_; }
    const SimulationConfig& config() const { return config_; }

    void start();
    void step(double dtSec);
    void stop();
    void reset();

    bool isRunning() const { return isRunning_.load(); }
    double getCurrentTime() const { return simNowSec_; }
    SystemMetrics getSystemMetrics() const;

    std::function<void(const SystemMetrics&)> onTick;

private:
    void generateRequests(double dtSec);
    void updateComponents(double dtSec);

    Component* getComponent(int id) const;
    Component* getEntryPoint() const;

    std::unordered_map<int, std::shared_ptr<Component>> components_;
    std::vector<std::shared_ptr<Request>> allRequests_;
    std::vector<double> completedLatenciesMs_;

    SimulationConfig config_;

    double simNowSec_ = 0.0;
    std::atomic<bool> isRunning_{false};
    uint64_t nextRequestId_ = 1;
    int entryPointId_ = -1;

    uint64_t totalRequests_ = 0;
    uint64_t completedRequests_ = 0;
    uint64_t failedRequests_ = 0;
    uint64_t droppedRequests_ = 0;
    double sumLatencyMs_ = 0.0;

    std::thread simThread_;
    mutable std::mutex engineMutex_;
};

// ─────────────────────────────────────────────────────────────────────────────
// 6. JSON Parser
// ─────────────────────────────────────────────────────────────────────────────

class JsonParser {
public:
    static void fillFromJson(SimulationEngine& engine, const nlohmann::json& j);
};

// ─────────────────────────────────────────────────────────────────────────────
// 7. Simulator Facade
// ─────────────────────────────────────────────────────────────────────────────

class Simulator {
public:
    Simulator();
    ~Simulator();

    void loadArchitecture(const std::string& architectureJson);
    void start();
    void step(double dtSec = 0.01);
    void stop();
    bool isRunning() const;
    SystemMetrics getMetrics() const;
    void reset();

private:
    std::unique_ptr<SimulationEngine> engine_;
    mutable std::mutex simMutex_;
};

} // namespace archisys
