#pragma once
#include <string>
#include <vector>
#include <cstdint>

namespace archisys {

/**
 * Request status throughout its lifecycle in the system.
 */
enum class RequestStatus {
    Created,     // Generated by client
    InQueue,     // Waiting in component FIFO queue
    Processing,  // Actively being processed by a worker
    Completed,   // Successfully completed
    Dropped,     // Dropped due to queue buffer overflow
    Failed       // Routing or internal error
};

/**
 * Records telemetry for a single component hop.
 */
struct RouteHop {
    int componentId = 0;
    std::string componentName = "";
    double queueWaitTimeMs = 0.0;
    double processingTimeMs = 0.0;
};

/**
 * A single transaction moving through the distributed architecture.
 */
struct Request {
    uint64_t id = 0;
    int clientId = 0;
    RequestStatus status = RequestStatus::Created;
    int currentComponentId = -1;

    double createdAtSec = 0.0;
    double completedAtSec = 0.0;

    // Cumulative latency in milliseconds
    double totalQueueWaitMs = 0.0;
    double totalProcessingMs = 0.0;

    // Route history
    std::vector<RouteHop> route;

    bool isDone() const {
        return status == RequestStatus::Completed ||
               status == RequestStatus::Dropped ||
               status == RequestStatus::Failed;
    }

    bool isSuccess() const {
        return status == RequestStatus::Completed;
    }

    double totalRoundTripMs() const {
        return totalQueueWaitMs + totalProcessingMs;
    }
};

} // namespace archisys
