#pragma once
#include <string>
#include <vector>
#include <cstdint>

namespace archisys {

/**
 * Status of a simulated request throughout its lifecycle in the system.
 */
enum class RequestStatus {
    Created,     // Newly generated by client, not yet queued
    InQueue,     // Waiting in a component's FIFO buffer
    Processing,  // Occupying an active worker instance slot
    Forwarded,   // Finished current component, being routed to the next
    Completed,   // Reached terminal destination or served successfully
    Failed,      // Failed due to error or routing fault
    Dropped      // Dropped because downstream queue was full (overflow)
};

inline const char* statusName(RequestStatus s) {
    switch (s) {
        case RequestStatus::Created:    return "Created";
        case RequestStatus::InQueue:    return "InQueue";
        case RequestStatus::Processing: return "Processing";
        case RequestStatus::Forwarded:  return "Forwarded";
        case RequestStatus::Completed:  return "Completed";
        case RequestStatus::Failed:     return "Failed";
        case RequestStatus::Dropped:    return "Dropped";
    }
    return "Unknown";
}

/**
 * RouteHop records the detailed timestamp and latency breakdown for a single
 * component visited along the request's journey through the architecture.
 */
struct RouteHop {
    int         componentId;
    std::string componentName;
    double      arrivalTime;      // Simulation time (seconds) when entering queue
    double      processingStart;  // Simulation time (seconds) when worker slot acquired
    double      departureTime;    // Simulation time (seconds) when finished processing
    double      queueWaitTimeMs;  // (processingStart - arrivalTime) * 1000
    double      processingTimeMs; // (departureTime - processingStart) * 1000
};

/**
 * Request represents a single discrete transaction moving through the simulated system.
 * It carries timing telemetry and hop-by-hop profiling data.
 */
struct Request {
    uint64_t      id                 = 0;
    uint64_t      clientId           = 0;
    double        createdAt          = 0.0; // Simulation time (seconds) when spawned
    double        completedAt        = 0.0; // Simulation time (seconds) when finalized
    RequestStatus status             = RequestStatus::Created;
    int           currentComponentId = -1;

    // Accumulated metrics across all hops
    double totalLatencyMs   = 0.0; // Total processing latency across all components (ms)
    double totalQueueWaitMs = 0.0; // Total queue waiting latency across all components (ms)

    // History of hops
    std::vector<RouteHop> route;

    bool isDone() const {
        return status == RequestStatus::Completed ||
               status == RequestStatus::Failed ||
               status == RequestStatus::Dropped;
    }

    bool isSuccess() const {
        return status == RequestStatus::Completed;
    }

    // End-to-end round trip latency from birth to completion (in milliseconds)
    double totalRoundTripMs(double simNow) const {
        if (completedAt > 0.0) return (completedAt - createdAt) * 1000.0;
        return (simNow - createdAt) * 1000.0;
    }
};

} // namespace archisys
